const COPY = {
  en: {
    step1Title: 'Install mode',
    step1Description: 'Choose how much setup to review.',
    simple: 'Simple',
    simpleCopy: 'Uses detected settings, accepts every choice and installs immediately.',
    custom: 'Custom',
    customCopy: 'Opens every installation setting before files are written.',
    step2Title: 'Mind location',
    step2Description: 'Choose the root folder for the mind.',
    step3Title: 'Agents',
    step3Description: 'Scan the machine and set how each agent loads HIVEM1ND.',
    agentsFound: 'Agents',
    attachModes: 'Attach mode',
    detected: 'Detected',
    manualSearch: 'Find an agent manually',
    onDemandTitle: 'On-demand mode',
    onDemandCopy: 'HIVEM1ND loads only when invoked. The agent does not read the mind rules automatically.',
    noAgentsDetected: 'No supported agents were detected on this machine.',
    step4Title: 'Content',
    step4Description: 'Select the features included in the mind.',
    nothingToInclude: 'No features or knowledge modules are available yet.',
    categoryPlanning: 'Planning',
    categoryQuality: 'Quality',
    categoryContinuity: 'Continuity',
    step5Title: 'Projects',
    step5Description: 'Confirm roots, optional environments and repositories.',
    step6Title: 'Confirm',
    step6Description: 'Set optional preferences and update checks.',
    addressUser: 'Address style',
    anythingElse: 'Additional instructions',
    keepExistingPreferences: 'Keep existing preferences first',
    updates: 'Automatically check for updates',
    step7Title: 'Install',
    step7Description: 'Review changes and resolve each conflict before installation.',
    confirmWrite: 'Install these files?',
    step8Title: 'Done',
    step8Description: 'Done. Run /executor <project> first.',
    language: 'Language',
    mindPath: 'Mind path',
    mindPathHelp: 'Local, synced, removable and network folders are supported.',
    installer: 'Installer folder',
    drive: 'C:\\',
    user: 'User',
    oneDrive: 'OneDrive',
    included: 'Features and knowledge',
    knowledgeModule: 'Knowledge module {name}',
    environment: 'Environment (optional)',
    environmentPlaceholder: 'Environment',
    addRoot: 'Add folder',
    removeRepository: 'Remove repository',
    removeEnvironment: 'Remove environment',
    projects: 'Confirm projects',
    skipPreferences: 'Skip all preferences',
    english: 'English',
    spanish: 'Spanish',
    scan: 'Scan for agents',
    onDemand: 'On demand',
    auto: 'Auto',
    impersonal: 'Impersonal',
    formal: 'Formal',
    explanatory: 'Explanatory',
    swarm: 'Swarm voice (“we”)',
    yes: 'Yes',
    no: 'No',
    keep: 'Keep existing file',
    replace: 'Replace with HIVEM1ND file',
    ownerMind: 'Mind',
    attachPrompt: 'Copy each Markdown file in {mind}/roles, {mind}/commands and {mind}/features, except README.md, to the agent command folder. Create one folder per file, use its frontmatter name and save the file as SKILL.md. Keep supported frontmatter and replace {{mind}} with {mind}. If the agent has no command folder, paste the body of a role file as the first chat message. For auto mode, add the following line to the agent rules file. “HIVEM1ND: the mind is at {mind}. Read {mind}/rules.md first, then the role or command asked for.”',
    back: 'Back',
    continue: 'Continue',
    install: 'Install',
    installing: 'Installing...',
    loading: 'Loading setup...',
    searchLanguages: 'Search languages',
    browse: 'Browse',
    add: 'Add',
    attachAuto: 'Auto-attach',
    attachOnDemand: 'On demand',
    noFiles: 'No files will be written.',
    filesCountOne: '{count} file',
    filesCountOther: '{count} files',
    firstCommand: 'First command',
    actionCreate: 'create',
    actionUpdate: 'update',
    actionUnchanged: 'unchanged',
    actionAppend: 'append',
    actionConflict: 'conflict',
    documentTitle: 'HIVEM1ND setup',
    warningNoAdapterAnother: 'No adapter is available for another agent. Use the attach prompt for {mind}.',
    warningNoAdapter: 'No adapter is available for {agent}. Use the attach prompt for {mind}.',
    warningNoRulesFile: '{agent} has no verified global rules file. Use the attach prompt for auto mode.',
    warningSymlinkSkipped: 'Skipped symbolic link in kit: {path}',
    warningUnsupportedEntry: 'Skipped unsupported kit entry: {path}',
    warningSymlinkDestinationSkippedOne: '{count} file skipped because its destination is a symbolic link.',
    warningSymlinkDestinationSkippedOther: '{count} files skipped because their destination is a symbolic link.',
    reasonDifferentContent: 'Two setup operations produce different content for this path.',
    reasonRulesNotRegular: 'The rules path is a symbolic link or is not a regular file.',
    reasonDestinationNotRegular: 'The destination is a symbolic link or is not a regular file.',
    reasonManagedFileModified: 'The HIVEM1ND-managed file was modified after installation.',
    reasonUnownedFile: 'An unowned file already exists at this path.',
    reasonAgentsConflict: 'Selected agents require different content at the same shared path.',
    reasonPathEscapes: 'Path escapes the selected destination: {path}',
    reasonDestinationRootNotDirectory: 'Destination root is not a directory: {path}',
    reasonDestinationComponentNotDirectory: 'Destination component is not a directory: {path}',
    reasonDestinationRootSymlink: 'Destination root is a symbolic link: {path}',
    reasonDestinationComponentSymlink: 'Destination component is a symbolic link: {path}',
    serverError: 'The local wizard could not complete the request.',
    sessionMissing: 'The local session link is incomplete. Open the wizard again from the HIVEM1ND command.',
    requestFailed: 'The local wizard request failed (status {status}).',
  },
  es: {
    step1Title: 'Modo de instalación',
    step1Description: 'Elegir cuánto revisar durante la instalación.',
    simple: 'Simple',
    simpleCopy: 'Usa la configuración detectada, acepta cada opción e instala de inmediato.',
    custom: 'Personalizada',
    customCopy: 'Abre cada ajuste de instalación antes de escribir archivos.',
    step2Title: 'Ubicación del mind',
    step2Description: 'Elegir la carpeta raíz del mind.',
    step3Title: 'Agentes',
    step3Description: 'Buscar agentes en la máquina y definir cómo carga HIVEM1ND cada uno.',
    agentsFound: 'Agentes',
    attachModes: 'Modo de conexión',
    detected: 'Detectado',
    manualSearch: 'Buscar un agente manualmente',
    onDemandTitle: 'Modo a demanda',
    onDemandCopy: 'HIVEM1ND carga solo cuando se lo invoca. El agente no lee automáticamente las reglas del mind.',
    noAgentsDetected: 'No se detectaron agentes admitidos en esta máquina.',
    step4Title: 'Contenido',
    step4Description: 'Seleccionar los features incluidos en el mind.',
    nothingToInclude: 'Todavía no hay features ni módulos de conocimiento disponibles.',
    categoryPlanning: 'Planificación',
    categoryQuality: 'Calidad',
    categoryContinuity: 'Continuidad',
    step5Title: 'Proyectos',
    step5Description: 'Confirmar raíces, entornos opcionales y repositorios.',
    step6Title: 'Confirmación',
    step6Description: 'Definir preferencias opcionales y la búsqueda de actualizaciones.',
    addressUser: 'Estilo de trato',
    anythingElse: 'Instrucciones adicionales',
    keepExistingPreferences: 'Respetar primero las preferencias existentes',
    updates: 'Buscar actualizaciones automáticamente',
    step7Title: 'Instalación',
    step7Description: 'Revisar los cambios y resolver cada conflicto antes de instalar.',
    confirmWrite: '¿Instalar estos archivos?',
    step8Title: 'Listo',
    step8Description: 'Listo. Ejecutar primero /executor <project>.',
    language: 'Idioma',
    mindPath: 'Ruta del mind',
    mindPathHelp: 'Admite carpetas locales, sincronizadas, removibles y de red.',
    installer: 'Carpeta del instalador',
    drive: 'C:\\',
    user: 'Usuario',
    oneDrive: 'OneDrive',
    included: 'Features y conocimiento',
    knowledgeModule: 'Módulo de conocimiento {name}',
    environment: 'Entorno (opcional)',
    environmentPlaceholder: 'Entorno',
    addRoot: 'Agregar carpeta',
    removeRepository: 'Quitar repositorio',
    removeEnvironment: 'Quitar entorno',
    projects: 'Confirmar proyectos',
    skipPreferences: 'Omitir todas las preferencias',
    english: 'Inglés',
    spanish: 'Español',
    scan: 'Buscar agentes',
    onDemand: 'A demanda',
    auto: 'Automático',
    impersonal: 'Impersonal',
    formal: 'Formal',
    explanatory: 'Explicativo',
    swarm: 'Voz del swarm (“nosotros”)',
    yes: 'Sí',
    no: 'No',
    keep: 'Conservar el archivo existente',
    replace: 'Reemplazar por el archivo de HIVEM1ND',
    ownerMind: 'Mind',
    attachPrompt: 'Copiar cada archivo Markdown de {mind}/roles, {mind}/commands y {mind}/features, excepto README.md, a la carpeta de comandos del agente. Crear una carpeta por archivo, usar su name del frontmatter y guardar el archivo como SKILL.md. Conservar el frontmatter admitido y reemplazar {{mind}} por {mind}. Si el agente no tiene una carpeta de comandos, pegar el cuerpo de un archivo de rol como primer mensaje del chat. Para el modo automático, agregar la siguiente línea al archivo de reglas del agente. “HIVEM1ND: the mind is at {mind}. Read {mind}/rules.md first, then the role or command asked for.”',
    back: 'Atrás',
    continue: 'Continuar',
    install: 'Instalar',
    installing: 'Instalando...',
    loading: 'Cargando configuración...',
    searchLanguages: 'Buscar idiomas',
    browse: 'Examinar',
    add: 'Agregar',
    attachAuto: 'Conexión automática',
    attachOnDemand: 'A demanda',
    noFiles: 'No se escribirá ningún archivo.',
    filesCountOne: '{count} archivo',
    filesCountOther: '{count} archivos',
    firstCommand: 'Primer comando',
    actionCreate: 'crear',
    actionUpdate: 'actualizar',
    actionUnchanged: 'sin cambios',
    actionAppend: 'agregar',
    actionConflict: 'conflicto',
    documentTitle: 'Configuración de HIVEM1ND',
    warningNoAdapterAnother: 'No hay un adapter disponible para otro agente. Usar el attach prompt para {mind}.',
    warningNoAdapter: 'No hay un adapter disponible para {agent}. Usar el attach prompt para {mind}.',
    warningNoRulesFile: '{agent} no tiene un archivo de reglas globales verificado. Usar el attach prompt para el modo automático.',
    warningSymlinkSkipped: 'Se omitió un symlink en el kit: {path}',
    warningUnsupportedEntry: 'Se omitió una entrada no admitida del kit: {path}',
    warningSymlinkDestinationSkippedOne: 'Se omitió {count} archivo porque su destino es un enlace simbólico.',
    warningSymlinkDestinationSkippedOther: 'Se omitieron {count} archivos porque su destino es un enlace simbólico.',
    reasonDifferentContent: 'Dos operaciones de configuración generan contenido distinto para esta ruta.',
    reasonRulesNotRegular: 'La ruta de reglas es un enlace simbólico o no es un archivo normal.',
    reasonDestinationNotRegular: 'El destino es un enlace simbólico o no es un archivo normal.',
    reasonManagedFileModified: 'El archivo administrado por HIVEM1ND fue modificado después de la instalación.',
    reasonUnownedFile: 'Ya existe un archivo ajeno a HIVEM1ND en esta ruta.',
    reasonAgentsConflict: 'Los agentes seleccionados requieren contenido distinto en la misma ruta compartida.',
    reasonPathEscapes: 'La ruta sale del destino seleccionado: {path}',
    reasonDestinationRootNotDirectory: 'La raíz de destino no es una carpeta: {path}',
    reasonDestinationComponentNotDirectory: 'Un componente del destino no es una carpeta: {path}',
    reasonDestinationRootSymlink: 'La raíz de destino es un enlace simbólico: {path}',
    reasonDestinationComponentSymlink: 'Un componente del destino es un enlace simbólico: {path}',
    serverError: 'La configuración local no pudo completar la solicitud.',
    sessionMissing: 'El enlace de la sesión local está incompleto. Abrir el asistente de nuevo desde el comando HIVEM1ND.',
    requestFailed: 'La solicitud del asistente local falló (estado {status}).',
  },
};

export const LANGUAGES = ['en', 'es'];

export function text(language, key, variables = {}) {
  const locale = language === 'es' ? 'es' : 'en';
  const value = COPY[locale][key];
  if (value === undefined) throw new Error(`Unknown setup text: ${key}`);
  return Object.entries(variables).reduce(
    (result, [name, replacement]) => result.replaceAll(`{${name}}`, String(replacement)),
    value,
  );
}

export function option(language, value, labelKey, hintKey) {
  const descriptor = { value, label: text(language, labelKey) };
  if (hintKey) descriptor.hint = text(language, hintKey);
  return descriptor;
}

export function detectLanguage(env = process.env) {
  const locale = env.LC_ALL || env.LC_MESSAGES || env.LANG || Intl.DateTimeFormat().resolvedOptions().locale || 'en';
  return String(locale).toLowerCase().startsWith('es') ? 'es' : 'en';
}
